### ISSUE TITLE
Doppelte Einträge über den Add-Button des jeweiligen Tages

### ISSUE THREAD

**Issue by drnoa** [opensource-challenge/opensource-challenge-client#24]
Heute wurde mein Eintrag in der Challenge doppelt gespeichert.
Den Eintrag habe ich unter: 
https://www.opensource-challenge.ch/post-contribution?date=2016-12-04
erstellt und nur einmal gespeichert.

**Comment by ombre8** [comment]
darfsch ned so fescht dröcke weisch ;)
