### ISSUE TITLE
Neuester Beitrag mit sonderbaren Zeichen

### ISSUE THREAD

**Issue by RetGal** [opensource-challenge/opensource-challenge-client#28]
Die "Neuester Beittrag von"-Zeile ist von zwei sonderbaren Chars umgeben [01F389] - hier werden sie korrekt dargestellt. (beobachtet mit FF 45.5.1 ESR)
🎉 Neuester Beitrag von Daniel Illi-Zuberbühler: Feature Request für ACLs in Rockstor kommentiert 🎉

**Comment by phil-pona** [comment]
same here: FF 50.0.2

![screen](https://cloud.githubusercontent.com/assets/11518264/20878429/31c23bcc-bacf-11e6-93db-157925eb50e0.png)

**Comment by Joshuasony** [comment]
using very official party-popper svg now...
