### ISSUE TITLE
"Denglisch" in template.hbs

### ISSUE THREAD

**Issue by kallies** [opensource-challenge/opensource-challenge-client#34]
Das Denglisch in template.hbs ("Die Contributors") mutet ein wenig nach ["Die, Contributors"](https://translate.google.com/#en/de/Die%2C%20Contributors) an. Ich schlage vor entweder einfach "Contributors" oder "Die Mitwirkenden" zu verwenden.

**Comment by Joshuasony** [comment]
recht hast du.
fixed evil text ;)
