### ISSUE TITLE
Link field mandatory

### ISSUE THREAD

**Issue by tobru** [opensource-challenge/opensource-challenge-client#45]
IMHO the link field should be mandatory. You know: We do Open Source =)

**Comment by ombre8** [comment]
Is there always a Link to an Opensource Contribution? In my opinion there are other ways to Contribute to Opensource than only in the Interwebs...

**Comment by Joshuasony** [comment]
@tobru can this issue be closed? Or should we discuss it further? I understand your point about open "source". 
IMHO actually only the title should be a mandatory field. Reasons being the following:
- Nobody has to proof anything to anybody
- You can't proof anything with a link
- For some contributions there are no links
- Many mandatory fields are annoying
- More mandatory fields result in unnecessary hurdle for submitting contributions
- Submitting contributions should be as simple as possible
