### ISSUE TITLE
Kommentar und Like-Funktion für Beiträge

### ISSUE THREAD

**Issue by sirtobey** [opensource-challenge/opensource-challenge-client#47]
Heute geht natürlich nichts mehr ohne dass man es _liken_ und _sharen_ kann - auch die Opensource Challenge nicht!

Daher hier mein Vorschlag, den Client (und das API) mit einer Kommentar- und Like-Funktion zu erweitern.
Eventuell könnte man die Likes auch noch als Metrik für den Wettbewerb nutzen  (anders als bei Facebook und Co. mit echten Auswirkungen!).

**Comment by ombre8** [comment]
Sharing shouldn't invade the users privacy, we should use something like Shariff: https://github.com/heiseonline/shariff

**Comment by schtibe** [comment]
@sirtobey Ich wäre mit einem Bewertungssystem vorsichtig. Die "Qualität" einer Contribution hängt ja stark von Faktoren wie verfügbare Zeit, Vorkenntnisse etc. ab. Wenn man nun ein Bewertungssystem einbaut, könnte dies viele Leute abschrecken, da sie keine Chance auf den Gewinn sehen [*] - was kontraproduktiv für den Sinn der Challenge wäre: jeden Tag etwas beizutragen - egal was, hauptsache *etwas*.

[*] und selbst wenn man hier mit "Hauptsache dabei" argumentiert, könnte es entmutigend wirken, wenn man keine Likes kriegt aber andere schon.

**Comment by ombre8** [comment]
@schtibe Ich würde glaubs aus deinen Gründen auf die Metrik verzichten, nicht zwingend auf den Like Button... Ich würde evtl auch eher einen Multiemotiondings einbauen, um ein kurzfeedback zu den Contributions zu ermöglichen, ählich wie hier auf Github oder auch Facebook...

**Comment by Joshuasony** [comment]
Ich fänds trotzdem eine nicht so schlechte Idee aus folgenden Gründen:
- Es motiviert, die einzelnen Beiträge genauer anzuschauen - dadurch kann man auch inspiriert werden
- Gute Leistungen werden mit "Likes" belohnt - dies ist eine positive Verstärkung der Beitragenden, was motivierend ist, weitere Beiträge zu submitten
- Anzahl likes können in einem gewissen Grad angeben, welche Beiträge von der Community besonders geschätzt werden. Diese könnten theoretisch auch besonders erwähnt oder andersweitig belohnt werden

Meines Erachtens überwiegen die Vorteile über den Nachteil, dass nicht alle Beiträge (gleich viele) Likes erhalten.
