### ISSUE TITLE
Mobile UI nicht so gäbig

### ISSUE THREAD

**Issue by ombre8** [opensource-challenge/opensource-challenge-client#48]
![screenshot_20161208-231746](https://cloud.githubusercontent.com/assets/2480918/21030038/bf9de11a-bd9c-11e6-850e-da98e565aedb.png)

Leider musste ich heute feststellen, dass niene Autokorektur viele fehler eingebaut hat ohne dass ich es sehen konnte...

**Comment by topaxi** [comment]
Fixed in a37adbd67d77af1e183f7bb3614a681942534b0f
