### ISSUE TITLE
Scollen auf iOS 

### ISSUE THREAD

**Issue by Joshuasony** [opensource-challenge/opensource-challenge-client#52]
Mit Safari und Chrome tritt auf dem iPhone SE ein Scroll-Problem auf: ich kann mit einer Wisch-Bewegung nicht schnell scrollen - es bleibt irgendwie hängen. Zudem funktioniert die ToTop-Funktion mit Klick auf die Taskbar nicht, welche normalerweise in allen Apps und besonders im Interwebs funzt. Haben andere dieses Issue auch?

**Comment by topaxi** [comment]
Funktioniert wohl nur wenn der ganze Body scrollbar ist. Habe einen kleinen fix gepusht, hilft der?

ToTop-Funktion funktioniert anscheinend nur mit "scrolling Body" Webseiten, kA ob wir da was machen können..

**Comment by Joshuasony** [comment]
your rock this shit! 
Aber Tap-auf-Taskbar-to-top funktioniert immer noch nicht - keine Ahnung an was das liegt.

**Comment by Joshuasony** [comment]
Ich schliesse das Issue, da das Scrolling nun normal funktioniert. Für das tap auf die Status Bar um nach oben zu gelangen können Apple User bei Bedarf ein neues Issue erfassen.
