### ISSUE TITLE
Mobile: Slidein Nav schliesst nicht

### ISSUE THREAD

**Issue by Joshuasony** [opensource-challenge/opensource-challenge-client#53]
Klickt man in der mobile Nav auf den Seitenlink, auf dem man sich bereits befindet, schliesst die Navigation nicht. Je nach Auflösung des Displays bleibt nicht mehr viel Platz, um neben die Navigation zu klicken/tapen, um diese damit zu schliessen. Ich würde erwarten, dass sich die Navigation schliesst, auch wenn ich den Link der Seite anklicke, auf der ich mich bereits befinde.

In diesem Zusammenhang kommt mir in den Sinn: evtl. wäre in der mobile Nav den active State anzuzeigen keine schlechte Sache. Eine Klasse wird bereits vergeben, das werde ich also noch stylen. Eventuell ist man dann auch weniger versucht, den Link anzuklicken, auf dem man sich bereits befindet :)

**Comment by topaxi** [comment]
Swipe nach links sollte Navigation auch schliessen (wie bei jeder App ^^).

Klick auf momentan aktiven Link zum Schliessen der Navigation klingt sinnvoll.

**Comment by Joshuasony** [comment]
Die Navigation verhält sich so, wie sie sollte. Vielen Dank Damian!
