### ISSUE TITLE
Sign in funktioniert nicht mehr 

### ISSUE THREAD

**Issue by sbaerlocher** [opensource-challenge/opensource-challenge-client#56]
Wenn ich mich einlogge mit dem Github Login, logt es mich anschliesend wieder aus. Dies passiert im Firefox 50 und im Chrome 55.

**Comment by topaxi** [comment]
Sollte sobald das Deploy fertig ist (5-10min) nach einem hardrefresh (ctrl+F5) wieder funktionieren.

**Comment by sbaerlocher** [comment]
Danke funktioniert wieder.
